
> user-service@1.0.0 dev
> nodemon --exec ts-node --transpileOnly -P tsconfig.json src/index.ts

[33m[nodemon] 3.1.10[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching path(s): *.*[39m
[33m[nodemon] watching extensions: ts,json[39m
[32m[nodemon] starting `ts-node --transpileOnly src/index.ts`[39m
[33mwarn[39m: JWT_SECRET not set; using insecure local development fallback. DO NOT use in production. {"timestamp":"2025-10-01T09:58:46.605Z"}
[dotenv@17.2.2] injecting env (8) from .env -- tip: üì° observe env with Radar: https://dotenvx.com/radar
[dotenv@17.2.2] injecting env (0) from .env -- tip: ‚öôÔ∏è  specify custom .env file path with { path: '/custom/path/.env' }
[32minfo[39m: Loaded environment for user-service {"timestamp":"2025-10-01T09:58:46.615Z"}
Error: listen EADDRINUSE: address already in use :::3002
    at Server.setupListenHandle [as _listen2] (node:net:1937:16)
    at listenInCluster (node:net:1994:12)
    at Server.listen (node:net:2099:7)
    at Function.listen (/Users/shouryaveersingh/Desktop/old data/staff/backend/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/Users/shouryaveersingh/Desktop/old data/staff/backend/services/user-service/src/index.ts:17:18)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Module.m._compile (/Users/shouryaveersingh/Desktop/old data/staff/backend/node_modules/ts-node/src/index.ts:1618:23)
    at loadTS (node:internal/modules/cjs/loader:1826:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/shouryaveersingh/Desktop/old data/staff/backend/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1469:32) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3002
}
[31m[nodemon] app crashed - waiting for file changes before starting...[39m
node:events:485
      throw er; // Unhandled 'error' event
      ^

Error: read EIO
    at TTY.onStreamRead (node:internal/stream_base_commons:216:20)
Emitted 'error' event on ReadStream instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -5,
  code: 'EIO',
  syscall: 'read'
}

Node.js v23.9.0
